--------------------------------------------------------------------------
--									--
--									--
--				ctrl.lua by By PureJuice		--
--									--
--									--
--------------------------------------------------------------------------
print( "Loading deathmatch Ctrl.lua" )

function config(map)
    MapCanSavePos(map, 0)		-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCopyNum(map, 1)			-- 1 Copy of the map will be generated by GameServer
    MapCopyStartType(map, 1) 		-- 设置地图立即开始
    SingleMapCopyPlyNum(map, 300) 	-- 300 Players are allowed to enter the map
    MapCanTeam(map , 1)			-- 1 = Allow players to create party // 0 = Do not allow players to create party
    MapType ( map , 4 )			-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
end


function get_map_entry_pos_deathmatch()   --设置入口的位置的坐标（坐标（米））

	local POS_X=2219
	local POS_Y=2779
	return POS_X , POS_Y

end

function init_entry(map)

    SetMapEntryMapName(map, "garner") --
    SetMapEntryTime(map, "2006/10/18/0/0", "0/24/0", "0/24/0", "0/24/0") 
   
end

function after_enter_deathmatch( role , map_copy )

local cha_name=GetChaDefaultName(role)

end

function before_leave_deathmatch ( role )

end

function map_copy_first_run_deathmatch( map_copy )



end

function map_copy_run_deathmatch( map_copy )



end

--每5秒执行一次的
function map_run_deathmatch( map )


end

--地图关闭时执行
function map_copy_close_deathmatch ( map_copy )

end
		
--地图开关判断——————————————————————————————————————————

function can_open_entry_deathmatch( map ) 

end 